CREATE TABLE member (
    id VARCHAR(6) NOT NULL PRIMARY KEY,
    name VARCHAR(16) NOT NULL
);

CREATE TABLE date (
    date DATE NOT NULL DEFAULT CURRENT_DATE PRIMARY KEY
);

CREATE TABLE attend (
    id VARCHAR(6) NOT NULL REFERENCES member(id),
    date DATE NOT NULL DEFAULT CURRENT_DATE REFERENCES date(date)
);